name: Testes Automatizados

on:
  push:
  pull_request:

jobs:
  testes:

    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Executar testes
        run: |
          pytest
